modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL = "https://github.com/Hunter19823/TwitchIntegration/issues"
license = "All Rights Reserved"

[[mods]]
    modId="twitchintegration"
    version="${file.jarVersion}"
    displayName="Twitch Integration"
    logoFile="Twitch4j.png"
    authors="ILIKEPIEFOO2"
    description='''
    The twitch4j library for minecraft.
    Now With Forge Events!
    '''

[[dependencies.twitchintegration]]
    modId="forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side="BOTH"