package pie.ilikepiefoo2.twitchintegration.events.autogenerated.com.github.twitch4j.chat.events.channel;


public class GlobalUserStateEventFE extends net.minecraftforge.eventbus.api.Event {
    public final com.github.twitch4j.chat.events.channel.GlobalUserStateEvent event;

    public GlobalUserStateEventFE( com.github.twitch4j.chat.events.channel.GlobalUserStateEvent event )
    {
        this.event = event;
    }

    public boolean equals( java.lang.Object arg0 ) // Declaring Class: com.github.twitch4j.chat.events.channel.GlobalUserStateEvent
    {
        return this.event.equals( arg0 );
    }
    public java.lang.String toString( ) // Declaring Class: com.github.twitch4j.chat.events.channel.GlobalUserStateEvent
    {
        return this.event.toString(  );
    }
    public int hashCode( ) // Declaring Class: com.github.twitch4j.chat.events.channel.GlobalUserStateEvent
    {
        return this.event.hashCode(  );
    }
    public java.util.Optional getDisplayName( ) // Declaring Class: com.github.twitch4j.chat.events.channel.GlobalUserStateEvent
    {
        return this.event.getDisplayName(  );
    }
    public java.util.Optional getUserId( ) // Declaring Class: com.github.twitch4j.chat.events.channel.GlobalUserStateEvent
    {
        return this.event.getUserId(  );
    }
    public boolean isPrimeOrTurbo( ) // Declaring Class: com.github.twitch4j.chat.events.channel.GlobalUserStateEvent
    {
        return this.event.isPrimeOrTurbo(  );
    }
    public java.util.List getEmoteSets( ) // Declaring Class: com.github.twitch4j.chat.events.channel.GlobalUserStateEvent
    {
        return this.event.getEmoteSets(  );
    }
    public boolean isStaff( ) // Declaring Class: com.github.twitch4j.chat.events.channel.GlobalUserStateEvent
    {
        return this.event.isStaff(  );
    }
    public java.util.Optional getColor( ) // Declaring Class: com.github.twitch4j.chat.events.channel.GlobalUserStateEvent
    {
        return this.event.getColor(  );
    }
    public com.github.twitch4j.chat.events.channel.IRCMessageEvent getMessageEvent( ) // Declaring Class: com.github.twitch4j.chat.events.channel.GlobalUserStateEvent
    {
        return this.event.getMessageEvent(  );
    }
    public com.github.twitch4j.chat.TwitchChat getTwitchChat( ) // Declaring Class: com.github.twitch4j.chat.events.TwitchEvent
    {
        return this.event.getTwitchChat(  );
    }
    public java.time.Instant getFiredAtInstant( ) // Declaring Class: com.github.philippheuer.events4j.core.domain.Event
    {
        return this.event.getFiredAtInstant(  );
    }
    public void setFiredAtInstant( java.time.Instant arg0 ) // Declaring Class: com.github.philippheuer.events4j.core.domain.Event
    {
        this.event.setFiredAtInstant( arg0 );
    }
    public void setEventId( java.lang.String arg0 ) // Declaring Class: com.github.philippheuer.events4j.core.domain.Event
    {
        this.event.setEventId( arg0 );
    }
    public java.lang.String getEventId( ) // Declaring Class: com.github.philippheuer.events4j.core.domain.Event
    {
        return this.event.getEventId(  );
    }
    public com.github.philippheuer.events4j.api.service.IServiceMediator getServiceMediator( ) // Declaring Class: com.github.philippheuer.events4j.core.domain.Event
    {
        return this.event.getServiceMediator(  );
    }
    public void setServiceMediator( com.github.philippheuer.events4j.api.service.IServiceMediator arg0 ) // Declaring Class: com.github.philippheuer.events4j.core.domain.Event
    {
        this.event.setServiceMediator( arg0 );
    }
    public java.util.Calendar getFiredAt( ) // Declaring Class: com.github.philippheuer.events4j.core.domain.Event
    {
        return this.event.getFiredAt(  );
    }
    public void setFiredAt( java.util.Calendar arg0 ) // Declaring Class: com.github.philippheuer.events4j.core.domain.Event
    {
        this.event.setFiredAt( arg0 );
    }

}
